shop/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .form import MyPasswordChangeForm,MyPasswordResetForm,MySetPasswordForm
from . import views
 
urlpatterns= [
    path('',views.home,name="home"),
    path('register',views.register,name="register"),
    path('login',views.login_page,name="login"),
    path('logout',views.logout_page,name="logout"),
    path('cart/',views.cart_page,name="cart"),
    path('fav',views.fav_page,name="fav"),
    path('favviewpage',views.favviewpage,name="favviewpage"),
    path('remove_fav/<str:fid>',views.remove_fav,name="remove_fav"),
    path('remove_cart/<str:cid>',views.remove_cart,name="remove_cart"),
    path('collections',views.collections,name="collections"),
    path('collections/<str:name>',views.collectionsview,name="collections"),
    path('collections/<str:cname>/<str:pname>',views.product_details,name="product_details"),
    path('addtocart',views.add_to_cart,name="addtocart"),
    path('collections/<str:cname>/<str:pname>/', views.product_detail, name='product_detail'),
    path('checkout/', views.checkout, name='checkout'),
    path('orders/', views.orders, name='orders'),
    path('save_address/', views.save_address, name='save_address'),
    path('saved_addresses/', views.saved_addresses, name='saved_addresses'),
    path('edit_address/<int:address_id>/', views.editAddress, name='edit_address'),
    path('update_cart_quantity/<int:item_id>/<int:new_quantity>/', views.update_cart_item_quantity, name='update_cart_quantity'),
    #path('payment/', views.payment, name='payment'),
    path('payment_done/', views.payment_done, name='payment_done'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/failure/', views.payment_failure, name='payment_failure'),

    # Passwords
     path("passwordchange/",auth_view.PasswordChangeView.as_view(template_name="password/changepassword.html",form_class=MyPasswordChangeForm, success_url="/passwordchangedone"),name="passwordchange"),
    path("passwordchangedone/",auth_view.PasswordChangeDoneView.as_view(template_name="password/passwordchangedone.html"),name="passwordchangedone"),
    path("password-reset/",auth_view.PasswordResetView.as_view(template_name="password/password_reset.html", form_class=MyPasswordResetForm),name="password_reset"),
    path("password-reset/done/",auth_view.PasswordResetDoneView.as_view(template_name="password/password_reset_done.html"),name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/",auth_view.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html",form_class=MySetPasswordForm),name="password_reset_confirm"),
    path("password-reset-complete/",auth_view.PasswordResetCompleteView.as_view(template_name="password/password_reset_complete.html"),name="password_reset_complete"),

]
 

skykart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/models.py
from contextlib import nullcontext
from itertools import product
from django.db import models
from django.contrib.auth.models import User
import datetime
import os

# Create your models here.

STATE_CHOICES =(
('Andaman & Nicobar Islands','Andaman & Nicobar Islands'),
('Andhra Pradesh','Andhra Pradesh'),
('Arunachal Pradesh','Arunachal Pradesh'),
('Assam','Assam'),
('Bihar','Bihar'),
('Chandigarh','Chandigarh' ),
('Chattisgarh','Chattisgarh'),
('Dadra & Nagar Haveli','Dadra & Nagar Haveli'),
('Daman and Diu','Daman and Diu'),
('Delhi','Delhi'),
('Goa','Goa'),
('Gujrat','Gujrat'),
('Haryana','Haryana') ,
('Himachal Pradesh','Himachal Pradesh') ,
('Jammu & Kashmir','Jammu & Kashmir'),
('Jharkhand','Jharkhand'),
('Karnataka','Karnataka'),
('Kerala','Kerala'),
('Lakshadweep','Lakshadweep'),
('Madhya Pradesh','Madhya Pradesh'),
('Maharashtra','Maharashtra') ,
('Manipur','Manipur'),
('Meghalaya','Meghalaya') ,
('Mizoram','Mizoram'),
('Nagaland','Nagaland'),
('Odisa','Odisa'),
('Puducherry','Puducherry'),
('Punjab','Punjab'),
('Rajasthan','Rajasthan'),
('Sikkim','Sikkim'),
('Tamilnadu','Tamilnadu'),
('Telangana','Telangana') ,
('Tripura','Tripura') ,
('Uttarakhand','Uttarakhand'),
('Uttar Pradesh','Uttar Pradesh'),
('West Bengal','West Bengal'),
)

def getFileName(requset,filename):
  now_time=datetime.datetime.now().strftime("%Y%m%d%H:%M:%S")
  new_filename="%s%s"%(now_time,filename)
  return os.path.join('uploads/',new_filename)
 
class Catagory(models.Model):
  name=models.CharField(max_length=150,null=False,blank=False)
  image=models.ImageField(upload_to=getFileName,null=True,blank=True)
  description=models.TextField(max_length=500,null=False,blank=False)
  status=models.BooleanField(default=False,help_text="0-show,1-Hidden")
  created_at=models.DateTimeField(auto_now_add=True)
 
  def __str__(self) :
    return self.name
 
class Product(models.Model):
  category=models.ForeignKey(Catagory,on_delete=models.CASCADE)
  name=models.CharField(max_length=150,null=False,blank=False)
  vendor=models.CharField(max_length=150,null=False,blank=False)
  product_image=models.ImageField(upload_to=getFileName,null=True,blank=True)
  quantity=models.IntegerField(null=False,blank=False)
  original_price=models.FloatField(null=False,blank=False)
  selling_price=models.FloatField(null=False,blank=False)
  description=models.TextField(max_length=500,null=False,blank=False)
  status=models.BooleanField(default=False,help_text="0-show,1-Hidden")
  trending=models.BooleanField(default=False,help_text="0-default,1-Trending")
  created_at=models.DateTimeField(auto_now_add=True)
 
  def __str__(self) :
    return self.name
 
class Cart(models.Model):
  user=models.ForeignKey(User,on_delete=models.CASCADE)
  product=models.ForeignKey(Product,on_delete=models.CASCADE)
  product_qty=models.IntegerField(null=False,blank=False)
  created_at=models.DateTimeField(auto_now_add=True)
 
  @property
  def total_cost(self):
    return self.product_qty*self.product.selling_price
 
class Favourite(models.Model):
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	product=models.ForeignKey(Product,on_delete=models.CASCADE)
	created_at=models.DateTimeField(auto_now_add=True)
        
class Address(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    address = models.TextField()
    state = models.CharField(choices=STATE_CHOICES,max_length=100)
    district = models.CharField(max_length=100)
    zip = models.CharField(max_length=10)
    address_type = models.CharField(max_length=10, choices=[('home', 'Home'), ('work', 'Work')])
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # Assuming you have a User model
    def __str__(self):
      return f"{self.first_name} {self.last_name}"

STATUS_CHOICES = (
   ('Accepted','Accepted'),
   ('Packed','Packed'),
   ('On the Way','On the Way'),
   ('Delivered','Delivered'),
   ('Cancel','Cancel'),
   ('Pending','Pending'),
)

class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.FloatField()
    razorpay_order_id = models.CharField(max_length=255,blank=True,null=True)
    payment_status = models.CharField(max_length=20,blank=True,null=True)
    payment_id = models.CharField(max_length=255,blank=True,null=True)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username} - {self.amount} - {self.payment_status}"

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    customer = models.CharField(max_length=255)
    product = models.CharField(max_length=255)
    quantity = models.PositiveIntegerField()
    ordered_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=30,choices=STATUS_CHOICES,default='Pending')
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.product} - {self.ordered_date}"
    

shop/templates/shop/address.html
{% extends 'shop/layouts/main.html' %}
{% block title %}
  Address | SkyKart
{% endblock title %}
{% block content %}
<div class="container my-5 py-5">
  <!--Section: Design Block-->
  <section>
    <div class="row">
      
      <div class="col-md-8 mb-4">
        <div class="card mb-4">
          <div class="card-header py-3">
            <h5 class="mb-0 text-font text-uppercase text-center">Delivery address</h5>
          </div>
          <div class="card-body">
            <form method="post" action="{% url 'save_address' %}">
              {% csrf_token %}
              <div class="row mb-4">
                <div class="col">
                  <div class="form-outline">
                      <label class="form-label" for="firstname">First name</label>
                      <input type="text" id="firstname" name="first_name" class="form-control" />
                      {% if form.errors.first_name %}
                        <p class="text-danger">{{ form.errors.first_name }}</p>
                      {% endif %}
                  </div>
                </div>
                <div class="col">
                  <div class="form-outline">
                      <label class="form-label" for="lastname">Last name</label>
                      <input type="text" id="lastname" name="last_name" class="form-control" />
                      {% if form.errors.last_name %}
                        <p class="text-danger">{{ form.errors.last_name }}</p>
                      {% endif %}
                  </div>
                </div>
              </div>

              <!-- Number input -->
              <div class="form-outline mb-4">
                  <label class="form-label" for="phone">Phone</label>
                  <input type="number" id="phone" name="phone" class="form-control" />
                  {% if form.errors.phone %}
                    <p class="text-danger">{{ form.errors.phone }}</p>
                  {% endif %}
              </div>

              <!-- Email input -->
              <div class="form-outline mb-4">
                  <label class="form-label" for="email">Email</label>
                  <input type="email" id="email" name="email" class="form-control"/>
                  {% if form.errors.email %}
                    <p class="text-danger">{{ form.errors.email }}</p>
                  {% endif %}
              </div>

              <!-- Address input -->
              <div class="form-outline mb-4">
                  <label class="form-label" for="address">Address</label>
                  <input type="text" id="address" name="address" class="form-control" placeholder="Door no, Street, City"/>
                  {% if form.errors.address %}
                    <p class="text-danger">{{ form.errors.address }}</p>
                  {% endif %}
              </div>

              <!-- State and District inputs -->
              <div class="row">
                <div class="col-md-6 mb-4">
                    <label class="form-label" for="state">State</label>
                    <input type="text" id="state" name="state" class="form-control form-control-lg" placeholder="Enter State">
                    {% if form.errors.state %}
                      <p class="text-danger">{{ form.errors.state }}</p>
                    {% endif %}
                </div>
                <div class="col-md-6 mb-4">
                    <label class="form-label" for="city">District</label>
                    <input type="text" id="city" name="district" class="form-control form-control-lg" placeholder="Enter District">
                    {% if form.errors.district %}
                      <p class="text-danger">{{ form.errors.district }}</p>
                    {% endif %}
                </div>
              </div>

              <div class="row">
                <div class="col-md-6 mb-4">
                    <label class="form-label" for="zipcode">Zip</label>
                    <input type="text" id="zipcode" name="zip" class="form-control form-control-lg" placeholder="Zipcode"/>
                    {% if form.errors.zip %}
                      <p class="text-danger">{{ form.errors.zip }}</p>
                    {% endif %}
                </div>
                <div class="col-md-6 mb-4 text-center">
                    <label class="form-label">Address Type</label><br>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="address_type" id="homeAddress" value="home">
                        <label class="form-check-label" for="homeAddress">Home</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="address_type" id="workAddress" value="work">
                        <label class="form-check-label" for="workAddress">Work</label>
                    </div>
                    {% if form.errors.addressType %}
                      <p class="text-danger">{{ form.errors.addressType }}</p>
                    {% endif %}
                </div>
              </div>

              <!-- Checkbox
              <div class="form-check d-flex justify-content-center mb-2">
                <input class="form-check-input me-2" type="checkbox" name="save_address" id="form11Example8" checked />
                <label class="form-check-label" for="form11Example8">
                  Save My Address
                </label>
                {% if form.errors.save_address %}
                  <p class="text-danger">{{ form.errors.save_address }}</p>
                {% endif %}
              </div>  -->
              <div class="text-center">
                <button type="submit" class="placeorderbtn bg-secondary text-font text-white col-md-10">Save Address</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="col-md-4 mb-4 position-static">
        <div class="address-page">
          <a href="{% url 'saved_addresses' %}" class="addressbtn btn-secondary">Show Addresses</a>
       </div>
       <br><br>
       <!--{% if form.errors %}
       {% for error in form.errors %}
         <p class="alert alert-danger my-3">{{error}}</p>
       {% endfor %}
     {% endif %}-->

     {% if messages %}
       {% for msg in messages %}
           <div class="alert alert-{{msg.tags}}" role="alert">
               {{msg}}
           </div>
       {% endfor %}
   {% endif %}           
      </div>
    </div>
  </section>
  <!--Section: Design Block-->
</div>
{% endblock content %}

shop/templates/shop/checkout.html
{% extends 'shop/layouts/main.html' %}
{% block title %}
  Checkout | SkyKart
{% endblock title %}

{% block content %}
<div class="container my-5 py-5">
  <!-- Section: Design Block -->
  <section>
    <div class="row">
      <!-- Cart Items -->
      <div class="col-md-4 mb-4 position-static">
        <div class="bg-secondary card mb-4">
          <div class="bg-dark card-header py-3 d-flex justify-content-between">
            <h5 class="mb-0 text-font text-warning text-uppercase">Cart Items</h5>
            <a href="{% url 'cart' %}">
              <button class="btn btn-secondary text-dark"><i class="fa fa-arrow-left me-2"></i>Back</button>
            </a>
          </div>
          <div class="card-body">
            {% for item in cart_items %}
            <div class="card mb-2 bg-secondary">
              <div class="card-body">
                <div class="row">
                  <div class="col-md-4">
                    <img src="{{ item.product.product_image.url }}" alt="{{ item.product.name }}" class="img-fluid">
                  </div>
                  <div class="col-md-8">
                    <h5 class="text-font text-warning">{{ item.product.name }}</h5>
                    <p>Quantity: {{ item.product_qty }}</p>
                    <p class="fw-bold bg-danger">Original Price: <strike>₹{{ item.product.original_price | stringformat:'d' }}</strike>/-</p>
                    <p class="fw-bold bg-success text-white">Selling Price: ₹{{ item.product.selling_price | stringformat:'d' }}/-</p>
                    <p class="fw-bold text-font">Total: ₹{{ item.total | floatformat:2 }}/-</p>
                  </div>
                </div>
              </div>
            </div>
            
            {% endfor %}
            <div class="bg-dark card-footer mt-4">
              <ul class="list-group list-group-flush">
                {% if total < 500 %}
                  <li class="bg-dark list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0 fw-bold text-warning">
                    SHIPPING CHARGE<small class="text-muted">(on orders below 500)</small>
                    <span>₹ 50/-</span>
                  </li>
                {% endif %}
                <li class="bg-dark text-warning list-group-item d-flex justify-content-between align-items-center px-0 fw-bold">
                  TOTAL TO PAY<small class="text-muted">(including GST)</small>
                  <span>₹ {{ cart_total | stringformat:'d' }}/-</span>
                </li>
              </ul>
            </div>            
              
          </div>
        </div>
      </div>

      <!-- Checkout Form -->
      <div class="col-md-8 mb-4">
        <div class="card mb-4 bg-secondary">
            <div class="card-header py-3 bg-dark">
                <h5 class="mb-0 text-font text-warning text-uppercase">Delivery address</h5>
            </div>
            <div class="card-body">
                <form method="post" id="AddressForm" .onclick="return validateForm();">
                    {% csrf_token %}
                    <div class="row">
                        {% for address in delivery_addresses %}
                        <div class="col-md-6 mb-4">
                            <div class="card">
                                <div class="card-header bg-dark text-font text-warning">
                                    Address {{ forloop.counter }}
                                </div>
                                <div class="card-body bg-secondary">
                                    <h5 class="card-title text-font text-center text-uppercase">{{ address.first_name }} {{ address.last_name }}</h5>
                                    <p class="card-text"><strong><i class="fa fa-phone"></i> Phone:</strong> {{ address.phone }}</p>
                                    <!--<p class="card-text"><strong><i class="fa fa-envelope"></i> Email:</strong> {{ address.email }}</p>-->
                                    <p class="card-text"><strong><i class="fa fa-map-marker"></i> Address:</strong> {{ address.address }}</p>
                                    <p class="card-text"><strong><i class="fa fa-location-arrow"></i> District:</strong> {{ address.district }}</p>
                                    <p class="card-text"><strong><i class="fa fa-flag"></i> State:</strong> {{ address.state }}</p>
                                    <p class="card-text"><strong><i class="fa fa-map-pin"></i> Zipcode:</strong> {{ address.zip }}</p>
                                    <p class="card-text"><strong><i class="fa fa-building"></i> Address Type:</strong> {{ address.get_address_type_display }}</p>
                                    <!-- Add more fields here -->
                                </div>
                                <div class="card-footer bg-dark">
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="selected_address" id="address{{ forloop.counter }}" value="{{ address.id }}">
                                        <label class="form-check-label text-font text-warning" for="address{{ forloop.counter }}">Select Address</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <!-- Place Order Button -->
                    <div class="card-footer bg-dark d-flex justify-content-between align-items-center">
                      <div class="text-center">
                        <a href="{% url 'save_address' %}" class="placeorderbtn btn-secondary text-font col-md-10"><i class="fa fa-plus"></i>Add New Address</a>
                      </div>
                      <!--<input type="hidden" name="cart_total" value={{ cart_total }}>-->
                      <div class="text-center">
                          <!-- <button type="submit" class="placeorderbtn bg-secondary text-warning text-font col-md-10">Place Order</button> -->
                          <button id="rzp-button1" type="button" class="placeorderbtn bg-secondary text-warning text-font col-md-10">Place Order</button>
                      </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <input type="hidden" name="order_id" value={{ order_id }}>
    <input type="hidden" name="user_id" value={{ user_id }}>
    </div>
  </section>
</div>
{% endblock content %}

{% block payment-gateway %}
<input type="hidden" name="order_id" value={{ order_id }}>
<input type="hidden" name="user_id" value={{ user_id }}>
<script>
  var order_id = document.querySelector('input[name="order_id"]').value;
  var user_id = document.querySelector('input[name="user_id"]').value;
  var options = {
    "key": "rzp_test_hVrvWFeoELiLve", // Enter the Key ID generated from the Dashboard
    "amount": "{{razoramount}}", // Amount is in currency subunits. Default currency is INR. For example, for ₹100, amount should be 10000
    "currency": "INR",
    "name": "SkyKart Corp", // Your business name
    "description": "Thanks for Shopping with us !",
    "image": "https://cdn.pixabay.com/photo/2018/08/04/15/37/shopping-3589969_1280.png", // Replace with the actual path to your favicon
    "order_id": "{{ order_id }}", // Use the order_id obtained from your payment processing
    "handler": function (response) {
      // Handle successful payment response here
      //console.log("Razorpay Response:", response);
      //var order_id = response.id;  // Use the Razorpay response ID as the order_id
      //var payment_id = response.razorpay_payment_id;
      window.location.href = `http://localhost:8000/payment_done/?order_id=${order_id}&payment_id=${response.razorpay_payment_id}&user_id=${user_id}`;
    },
    "prefill": {
      // We recommend pre-filling customer's contact information
      "name": "{{ request.user.first_name }}", // Replace with actual user's first name
      "email": "{{ request.user.email }}", // Replace with actual user's email
      //"contact": "{{ request.user.profile.phone }}" // Replace with actual user's phone number
    },
    "theme": {
      "color": "#3399cc"
    }
  };

  var rzp1 = new Razorpay(options);

  rzp1.on('payment.failed', function (response) {
    // Handle payment failure here
    alert(response.error.description);
  });

  document.getElementById('rzp-button1').onclick = function (e) {
    console.log("Button clicked");
    var selectedAddress = document.querySelector('input[name="selected_address"]:checked');
    if (!selectedAddress) {
      alert("Please select a delivery address before placing the order.");
      return; // Prevent Razorpay from opening if address not selected
    }
    rzp1.open();
    e.preventDefault();
  };
</script>

{% endblock payment-gateway %}

{% block scripts %}
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
{% endblock scripts %}

shop/templates/shop/collections.html
{% extends 'shop/layouts/main.html' %}
{% block title %}
  Products | SkyKart
{% endblock title %}
{% block content %}
  <!--<section class="py-2 text-center bg-dark"  style="margin-top:70px;">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h2 class="text-heading text-warning">BESTSELLERS</h2>
        <p class="lead text-muted">Our most popular products based on sales. Updated hourly.</p>
        {% if not user.is_authenticated %}
          <p>
            <a href="{% url 'login' %}" class="btn btn-primary my-2">Already User</a>
            <a href="{% url 'register' %}" class="btn btn-secondary my-2">Register</a>
          </p>
        {% endif %}
      </div>
    </div>
  </section>-->
  <hr class="text-dark">
  <section class="bg-secondary py-0 my-5" style="min-height:600px;">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h3 class="mb-3 text-center text-warning text-heading">CATEGORIES</h3>
          <hr style="border-color:#b8bfc2;">
          {% include 'shop/inc/message.html' %}
        </div>
        {% for item in catagory %}
        <div class="col-md-4 col-lg-3">
          <div class="card my-3 bg-dark">
            <a href="{% url 'collections' item.name %}">
            <img src="{{item.image.url}}"  class="card-img-top" alt="Categories">
            <div class="card-body">
              <h5 class="card-title text-font text-center text-warning">{{ item.name }}</h5>
              <p class="card-text text-muted">{{ item.description }}</p>
            </div>
          </a>
          </div>
        </div>
        {% endfor %}
      </div>
      </div>
  </section>

{% endblock content %}

shop/templates/shop/fav.html
{% extends 'shop/layouts/main.html' %}
{% block title %}
  Favourites | SkyKart
{% endblock title %}
{% block content %}
  <section class="bg-dark py-4 my-5" style="min-height:600px;">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h4 class="mb-3">Favourite Items</h4>
          <hr style="border-color:#b8bfc2;">
        </div>
        {% if fav %}
          <table class="text-center">
              <tr class="text-warning">
                  <th></th>
                  <th>Product Name</th>
                  <th>Price</th>
                  <th>Add to Cart</th>
                  <th></th>
              </tr>

              {% for item in fav %}
                <tr class="text-white">
                  <td>
                    <a href="{% url 'product_detail' item.product.category.name item.product.name %}">
                      <img src="{{item.product.product_image.url}}" height="100px" width="150px" alt="{{item.product.name}}">
                    </a>
                  </td>
                  <td>{{item.product.name}}</td>
                  <td>{{item.product.selling_price | stringformat:'d'}}</td>
                  <td>
                    {% if item.product.quantity > 0 %}
                      <input type="hidden" value="{{ item.product.id }}" class="pid">
                      <button class="cartbtn btn-primary" id="btnCart"><i class="fa fa-shopping-cart text-warning"></i> Add to Cart</button>
                    {% else %}
                      <button class="cartbtn btn-secondary"><i class="fa fa-minus"></i> Out of Stock</button>
                    {% endif %}
                  </td>
                  <td>
                    <a href="{% url 'remove_fav' item.id %}" onclick="return confirm('Are you sure? to Remove')" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Remove</a>
                  </td>
                </tr>
              {% endfor %}
              <tr>
          </table>
        <!-- Display a button to add favorites when the list is empty -->
        {% else %}
          <div class="empty-page">
            <p class="text-warning"><b>You have no favorite items yet !</b></p>
            <a href="{% url 'collections' %}" class="btn btn-primary">Add Favorites</a>
          </div>
        {% endif %}
      </div>
    </div>
  </section>
  <script>
    const cartButtons = document.querySelectorAll('.cartbtn');
    cartButtons.forEach(button => {
      button.addEventListener('click', function() {
        const row = button.closest('tr');
        const pid = row.querySelector('.pid').value;

        const postObj = { 
          'product_qty': 1, 
          'pid': pid
        };

        fetch("/addtocart",{
          method: 'POST',
          credentials: 'same-origin',
          headers: {
            'Accept': 'application/json',
            'X-Requested-With': 'XMLHttpRequest',
            'X-CSRFToken': '{{ csrf_token }}',
          },
          body: JSON.stringify(postObj)
        }).then(response => {
          return response.json();
        }).then(data => {
          alert(data['status']);
        });
      });
    });
  </script>
{% endblock content %}

shop/templates/shop/saved_addresses.html
{% extends 'shop/layouts/main.html' %}
{% block title %}
  Saved Addresses | SkyKart
{% endblock title %}
{% block content %}
<div class="container my-5 py-5">
  <h1 class="mb-4 address-font text-uppercase">Saved Addresses</h1><hr class="hr text-warning">
  {% if addresses %}
    <div class="row row-cols-1 row-cols-md-2 g-4">
      {% for address in addresses %}
        <div class="col">
          <div class="card">
            <div class="card-header bg-dark text-font text-warning">
              Address {{ forloop.counter }}
            </div>
            <div class="card-body bg-secondary">
              <h5 class="card-title text-font text-center text-uppercase">{{ address.first_name }} {{ address.last_name }}</h5>
              <p class="card-text"><strong><i class="fa fa-phone"></i> Phone:</strong> {{ address.phone }}</p>
              <p class="card-text"><strong><i class="fa fa-envelope"></i> Email:</strong> {{ address.email }}</p>
              <p class="card-text"><strong><i class="fa fa-map-marker"></i> Address:</strong> {{ address.address }}</p>
              <p class="card-text"><strong><i class="fa fa-location-arrow"></i> District:</strong> {{ address.district }}</p>
              <p class="card-text"><strong><i class="fa fa-flag"></i> State:</strong> {{ address.state }}</p>
              <p class="card-text"><strong><i class="fa fa-map-pin"></i> Zipcode:</strong> {{ address.zip }}</p>
              <p class="card-text"><strong><i class="fa fa-building"></i> Address Type:</strong> {{ address.get_address_type_display }}</p>
              <!-- Add more fields here -->
            </div>
            <div class="card-footer bg-dark">
              <div class="d-flex justify-content-between">
                <p class="mb-0"></p>
                <a href="{% url 'edit_address' address.id %}" class="editbtn btn-secondary text-warning"><i class="fa fa-edit"></i>Edit</a>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
  <div class="card-body bg-dark">
    <p class="text-font text-danger text-center">You have no saved Address yet!</p>
  </div>
  <div class="card-footer bg-dark d-flex justify-content-center">
    <a href="{% url 'save_address' %}" class="btn btn-success text-font text-dark  mt-3">Add Now</a>
  </div>
  {% endif %}
</div>
{% endblock content %}